# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.2.0/rest-clients.json
RestClients:
  #GitHub's v3 REST API.
  github (GitHub v3 REST API):
    UUID: 4895b78f-4d15-49f6-9754-de015d91d52e
    Url: https://api.github.com
    Icon: res:/webContent/icons/GitHub-Mark-64px.png
    Features:
    - ch.ivyteam.ivy.rest.client.authentication.HttpBasicAuthenticationFeature
    - com.axonivy.connector.github.odata.OpenApiJsonFeature
    Properties:
      username: ''
      password: ${decrypt:YPre0uLvtQxBFdWt2D9Tu7UY6RZRmyXr4N69dARQz4RBt3M6Z0loyjpUoHK+jO6Z6YQ3zo0jKDyfeQ2fd35sjg==}
    OpenAPI:
      SpecUrl: file:///C:/work/axonivy-market/market-products/github-connector/api.github.com.json
      Namespace: com.github.api.client
